"""Database seeder for initial stock population."""

import logging
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorDatabase

logger = logging.getLogger(__name__)

POPULAR_STOCKS = [
    # US Stocks
    {
        "symbol": "AAPL",
        "company_name": "Apple Inc.",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "exchange": "NASDAQ",
        "current_price": 180.25,
        "market_cap": 2800000000000.0,
        "description": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
        "logo_url": "https://logo.clearbit.com/apple.com",
        "website": "https://www.apple.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "MSFT",
        "company_name": "Microsoft Corporation",
        "sector": "Technology",
        "industry": "Software - Infrastructure",
        "exchange": "NASDAQ",
        "current_price": 420.50,
        "market_cap": 3100000000000.0,
        "description": "Microsoft Corporation develops and supports software, services, devices, and solutions worldwide.",
        "logo_url": "https://logo.clearbit.com/microsoft.com",
        "website": "https://www.microsoft.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "NVDA",
        "company_name": "NVIDIA Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "exchange": "NASDAQ",
        "current_price": 875.12,
        "market_cap": 2200000000000.0,
        "description": "NVIDIA Corporation focuses on personal computer graphics, graphics processing units, and also on artificial intelligence solutions.",
        "logo_url": "https://logo.clearbit.com/nvidia.com",
        "website": "https://www.nvidia.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "AMZN",
        "company_name": "Amazon.com, Inc.",
        "sector": "Consumer Cyclical",
        "industry": "Internet Retail",
        "exchange": "NASDAQ",
        "current_price": 178.15,
        "market_cap": 1850000000000.0,
        "description": "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally.",
        "logo_url": "https://logo.clearbit.com/amazon.com",
        "website": "https://www.amazon.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "GOOGL",
        "company_name": "Alphabet Inc.",
        "sector": "Communication Services",
        "industry": "Internet Content & Information",
        "exchange": "NASDAQ",
        "current_price": 150.80,
        "market_cap": 1880000000000.0,
        "description": "Alphabet Inc. offers various platforms and services in the United States, Europe, the Americas, and the Asia-Pacific.",
        "logo_url": "https://logo.clearbit.com/google.com",
        "website": "https://www.google.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "META",
        "company_name": "Meta Platforms, Inc.",
        "sector": "Communication Services",
        "industry": "Internet Content & Information",
        "exchange": "NASDAQ",
        "current_price": 490.22,
        "market_cap": 1250000000000.0,
        "description": "Meta Platforms, Inc. focuses on building products that enable people to connect and share through mobile devices, personal computers, virtual reality headsets, and wearables.",
        "logo_url": "https://logo.clearbit.com/meta.com",
        "website": "https://www.meta.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "TSLA",
        "company_name": "Tesla, Inc.",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "exchange": "NASDAQ",
        "current_price": 175.40,
        "market_cap": 550000000000.0,
        "description": "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems.",
        "logo_url": "https://logo.clearbit.com/tesla.com",
        "website": "https://www.tesla.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "NFLX",
        "company_name": "Netflix, Inc.",
        "sector": "Communication Services",
        "industry": "Entertainment",
        "exchange": "NASDAQ",
        "current_price": 610.50,
        "market_cap": 260000000000.0,
        "description": "Netflix, Inc. provides entertainment services with paid memberships in approximately 190 countries.",
        "logo_url": "https://logo.clearbit.com/netflix.com",
        "website": "https://www.netflix.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "AMD",
        "company_name": "Advanced Micro Devices, Inc.",
        "sector": "Technology",
        "industry": "Semiconductors",
        "exchange": "NASDAQ",
        "current_price": 170.18,
        "market_cap": 275000000000.0,
        "description": "Advanced Micro Devices, Inc. operates as a semiconductor company worldwide.",
        "logo_url": "https://logo.clearbit.com/amd.com",
        "website": "https://www.amd.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "INTC",
        "company_name": "Intel Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "exchange": "NASDAQ",
        "current_price": 38.40,
        "market_cap": 160000000000.0,
        "description": "Intel Corporation designs, manufactures, and sells computer components and related products for business and consumer markets worldwide.",
        "logo_url": "https://logo.clearbit.com/intel.com",
        "website": "https://www.intel.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "AVGO",
        "company_name": "Broadcom Inc.",
        "sector": "Technology",
        "industry": "Semiconductors",
        "exchange": "NASDAQ",
        "current_price": 1350.00,
        "market_cap": 625000000000.0,
        "description": "Broadcom Inc. designs, develops, and supplies various semiconductor and infrastructure software solutions.",
        "logo_url": "https://logo.clearbit.com/broadcom.com",
        "website": "https://www.broadcom.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "QCOM",
        "company_name": "QUALCOMM Incorporated",
        "sector": "Technology",
        "industry": "Semiconductors",
        "exchange": "NASDAQ",
        "current_price": 165.50,
        "market_cap": 185000000000.0,
        "description": "QUALCOMM Incorporated engages in the development and commercialization of foundational technologies for the wireless industry.",
        "logo_url": "https://logo.clearbit.com/qualcomm.com",
        "website": "https://www.qualcomm.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "ADBE",
        "company_name": "Adobe Inc.",
        "sector": "Technology",
        "industry": "Software - Infrastructure",
        "exchange": "NASDAQ",
        "current_price": 485.60,
        "market_cap": 218000000000.0,
        "description": "Adobe Inc. operates as a diversified software company worldwide.",
        "logo_url": "https://logo.clearbit.com/adobe.com",
        "website": "https://www.adobe.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "CSCO",
        "company_name": "Cisco Systems, Inc.",
        "sector": "Technology",
        "industry": "Communication Equipment",
        "exchange": "NASDAQ",
        "current_price": 48.20,
        "market_cap": 195000000000.0,
        "description": "Cisco Systems, Inc. designs, manufactures, and sells Internet Protocol-based networking and other products.",
        "logo_url": "https://logo.clearbit.com/cisco.com",
        "website": "https://www.cisco.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "WMT",
        "company_name": "Walmart Inc.",
        "sector": "Consumer Defensive",
        "industry": "Discount Stores",
        "exchange": "NYSE",
        "current_price": 60.10,
        "market_cap": 480000000000.0,
        "description": "Walmart Inc. operates supercenters, supermarkets, hypermarkets, warehouse clubs, cash and carry stores, and discount stores worldwide.",
        "logo_url": "https://logo.clearbit.com/walmart.com",
        "website": "https://www.walmart.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "DIS",
        "company_name": "The Walt Disney Company",
        "sector": "Communication Services",
        "industry": "Entertainment",
        "exchange": "NYSE",
        "current_price": 115.50,
        "market_cap": 210000000000.0,
        "description": "The Walt Disney Company operates as an entertainment company worldwide.",
        "logo_url": "https://logo.clearbit.com/disney.com",
        "website": "https://thewaltdisneycompany.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "V",
        "company_name": "Visa Inc.",
        "sector": "Financial Services",
        "industry": "Credit Services",
        "exchange": "NYSE",
        "current_price": 275.40,
        "market_cap": 570000000000.0,
        "description": "Visa Inc. operates as a payments technology company worldwide.",
        "logo_url": "https://logo.clearbit.com/visa.com",
        "website": "https://www.visa.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "MA",
        "company_name": "Mastercard Incorporated",
        "sector": "Financial Services",
        "industry": "Credit Services",
        "exchange": "NYSE",
        "current_price": 465.10,
        "market_cap": 435000000000.0,
        "description": "Mastercard Incorporated, a technology company, provides transaction processing and other payment-related products and services.",
        "logo_url": "https://logo.clearbit.com/mastercard.com",
        "website": "https://www.mastercard.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "JPM",
        "company_name": "JPMorgan Chase & Co.",
        "sector": "Financial Services",
        "industry": "Banks - Diversified",
        "exchange": "NYSE",
        "current_price": 195.20,
        "market_cap": 560000000000.0,
        "description": "JPMorgan Chase & Co. operates as a financial services company worldwide.",
        "logo_url": "https://logo.clearbit.com/jpmorganchase.com",
        "website": "https://www.jpmorganchase.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "KO",
        "company_name": "The Coca-Cola Company",
        "sector": "Consumer Defensive",
        "industry": "Beverages - Non-Alcoholic",
        "exchange": "NYSE",
        "current_price": 60.40,
        "market_cap": 260000000000.0,
        "description": "The Coca-Cola Company, a beverage company, manufactures, markets, and sells various non-alcoholic beverages worldwide.",
        "logo_url": "https://logo.clearbit.com/coca-cola.com",
        "website": "https://www.coca-colacompany.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "PEP",
        "company_name": "PepsiCo, Inc.",
        "sector": "Consumer Defensive",
        "industry": "Beverages - Non-Alcoholic",
        "exchange": "NASDAQ",
        "current_price": 172.50,
        "market_cap": 236000000000.0,
        "description": "PepsiCo, Inc. manufactures, markets, distributes, and sells various beverages, foods, and snacks worldwide.",
        "logo_url": "https://logo.clearbit.com/pepsico.com",
        "website": "https://www.pepsico.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "COST",
        "company_name": "Costco Wholesale Corporation",
        "sector": "Consumer Defensive",
        "industry": "Discount Stores",
        "exchange": "NASDAQ",
        "current_price": 725.30,
        "market_cap": 322000000000.0,
        "description": "Costco Wholesale Corporation operates membership warehouses in the United States and internationally.",
        "logo_url": "https://logo.clearbit.com/costco.com",
        "website": "https://www.costco.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "ORCL",
        "company_name": "Oracle Corporation",
        "sector": "Technology",
        "industry": "Software - Infrastructure",
        "exchange": "NYSE",
        "current_price": 125.40,
        "market_cap": 345000000000.0,
        "description": "Oracle Corporation offers products and services that address enterprise information technology environments worldwide.",
        "logo_url": "https://logo.clearbit.com/oracle.com",
        "website": "https://www.oracle.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "CRM",
        "company_name": "Salesforce, Inc.",
        "sector": "Technology",
        "industry": "Software - Application",
        "exchange": "NYSE",
        "current_price": 290.10,
        "market_cap": 280000000000.0,
        "description": "Salesforce, Inc. provides customer relationship management technology that brings companies and customers together.",
        "logo_url": "https://logo.clearbit.com/salesforce.com",
        "website": "https://www.salesforce.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },
    {
        "symbol": "NKE",
        "company_name": "NIKE, Inc.",
        "sector": "Consumer Cyclical",
        "industry": "Footwear & Accessories",
        "exchange": "NYSE",
        "current_price": 100.80,
        "market_cap": 152000000000.0,
        "description": "NIKE, Inc., together with its subsidiaries, designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories.",
        "logo_url": "https://logo.clearbit.com/nike.com",
        "website": "https://www.nike.com",
        "country": "United States",
        "currency": "USD",
        "is_active": True
    },

    # Indian Stocks
    {
        "symbol": "INFY.NS",
        "company_name": "Infosys Limited",
        "sector": "Technology",
        "industry": "Information Technology Services",
        "exchange": "NSE",
        "current_price": 1500.50,
        "market_cap": 6200000000000.0,
        "description": "Infosys Limited provides consulting, technology, outsourcing, and next-generation digital services in North America, Europe, India, and internationally.",
        "logo_url": "https://logo.clearbit.com/infosys.com",
        "website": "https://www.infosys.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "TCS.NS",
        "company_name": "Tata Consultancy Services Limited",
        "sector": "Technology",
        "industry": "Information Technology Services",
        "exchange": "NSE",
        "current_price": 3950.00,
        "market_cap": 14000000000000.0,
        "description": "Tata Consultancy Services Limited provides information technology, consulting, and business solutions worldwide.",
        "logo_url": "https://logo.clearbit.com/tcs.com",
        "website": "https://www.tcs.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "RELIANCE.NS",
        "company_name": "Reliance Industries Limited",
        "sector": "Energy",
        "industry": "Oil & Gas Refining & Marketing",
        "exchange": "NSE",
        "current_price": 2920.40,
        "market_cap": 19800000000000.0,
        "description": "Reliance Industries Limited engages in hydrocarbon exploration and production, petroleum refining and marketing, petrochemicals, retail, and digital services businesses worldwide.",
        "logo_url": "https://logo.clearbit.com/relianceindustries.com",
        "website": "https://www.ril.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "HDFCBANK.NS",
        "company_name": "HDFC Bank Limited",
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "exchange": "NSE",
        "current_price": 1450.80,
        "market_cap": 11000000000000.0,
        "description": "HDFC Bank Limited provides a range of banking and financial services to individuals and businesses in India, Bahrain, Hong Kong, and Singapore.",
        "logo_url": "https://logo.clearbit.com/hdfcbank.com",
        "website": "https://www.hdfcbank.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "ICICIBANK.NS",
        "company_name": "ICICI Bank Limited",
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "exchange": "NSE",
        "current_price": 1080.20,
        "market_cap": 7500000000000.0,
        "description": "ICICI Bank Limited provides banking and financial services in India and internationally.",
        "logo_url": "https://logo.clearbit.com/icicibank.com",
        "website": "https://www.icicibank.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "SBIN.NS",
        "company_name": "State Bank of India",
        "sector": "Financial Services",
        "industry": "Banks - Diversified",
        "exchange": "NSE",
        "current_price": 760.50,
        "market_cap": 6800000000000.0,
        "description": "State Bank of India provides a range of banking and financial services in India and internationally.",
        "logo_url": "https://logo.clearbit.com/sbi.co.in",
        "website": "https://www.sbi.co.in",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "LT.NS",
        "company_name": "Larsen & Toubro Limited",
        "sector": "Industrials",
        "industry": "Engineering & Construction",
        "exchange": "NSE",
        "current_price": 3750.15,
        "market_cap": 5200000000000.0,
        "description": "Larsen & Toubro Limited engages in engineering, construction, manufacturing, and IT services worldwide.",
        "logo_url": "https://logo.clearbit.com/larsentoubro.com",
        "website": "https://www.larsentoubro.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "AXISBANK.NS",
        "company_name": "Axis Bank Limited",
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "exchange": "NSE",
        "current_price": 1050.40,
        "market_cap": 3200000000000.0,
        "description": "Axis Bank Limited provides suite of corporate and retail banking services in India and internationally.",
        "logo_url": "https://logo.clearbit.com/axisbank.com",
        "website": "https://www.axisbank.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "TITAN.NS",
        "company_name": "Titan Company Limited",
        "sector": "Consumer Cyclical",
        "industry": "Luxury Goods",
        "exchange": "NSE",
        "current_price": 3600.00,
        "market_cap": 3200000000000.0,
        "description": "Titan Company Limited manufactures and sells watches, jewelry, eyewear, and other accessories in India and internationally.",
        "logo_url": "https://logo.clearbit.com/titan.co.in",
        "website": "https://www.titancompany.in",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "WIPRO.NS",
        "company_name": "Wipro Limited",
        "sector": "Technology",
        "industry": "Information Technology Services",
        "exchange": "NSE",
        "current_price": 480.20,
        "market_cap": 2500000000000.0,
        "description": "Wipro Limited operates as an information technology, consulting, and business process services company worldwide.",
        "logo_url": "https://logo.clearbit.com/wipro.com",
        "website": "https://www.wipro.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "TATAMOTORS.NS",
        "company_name": "Tata Motors Limited",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "exchange": "NSE",
        "current_price": 980.40,
        "market_cap": 3250000000000.0,
        "description": "Tata Motors Limited designs, manufactures, and sells a wide range of automotive vehicles in India and globally.",
        "logo_url": "https://logo.clearbit.com/tatamotors.com",
        "website": "https://www.tatamotors.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "BHARTIARTL.NS",
        "company_name": "Bharti Airtel Limited",
        "sector": "Communication Services",
        "industry": "Telecom Services",
        "exchange": "NSE",
        "current_price": 1200.80,
        "market_cap": 6800000000000.0,
        "description": "Bharti Airtel Limited operates as a telecommunications services company internationally.",
        "logo_url": "https://logo.clearbit.com/airtel.in",
        "website": "https://www.airtel.in",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "ITC.NS",
        "company_name": "ITC Limited",
        "sector": "Consumer Defensive",
        "industry": "Tobacco",
        "exchange": "NSE",
        "current_price": 425.40,
        "market_cap": 5300000000000.0,
        "description": "ITC Limited manufactures and sells fast moving consumer goods, hotels, paperboards, packaging, and agri-business products.",
        "logo_url": "https://logo.clearbit.com/itcportal.com",
        "website": "https://www.itcportal.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "KOTAKBANK.NS",
        "company_name": "Kotak Mahindra Bank Limited",
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "exchange": "NSE",
        "current_price": 1780.00,
        "market_cap": 3500000000000.0,
        "description": "Kotak Mahindra Bank Limited provides a range of banking and financial services to corporate and individual customers in India.",
        "logo_url": "https://logo.clearbit.com/kotak.com",
        "website": "https://www.kotak.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "SUNPHARMA.NS",
        "company_name": "Sun Pharmaceutical Industries Limited",
        "sector": "Healthcare",
        "industry": "Drug Manufacturers - Specialty & Generic",
        "exchange": "NSE",
        "current_price": 1540.30,
        "market_cap": 3700000000000.0,
        "description": "Sun Pharmaceutical Industries Limited manufactures and markets pharmaceutical formulations, active pharmaceutical ingredients, and intermediates.",
        "logo_url": "https://logo.clearbit.com/sunpharma.com",
        "website": "https://www.sunpharma.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "HINDUNILVR.NS",
        "company_name": "Hindustan Unilever Limited",
        "sector": "Consumer Defensive",
        "industry": "Household & Personal Products",
        "exchange": "NSE",
        "current_price": 2420.50,
        "market_cap": 5700000000000.0,
        "description": "Hindustan Unilever Limited manufactures, markets, and sells consumer goods in India.",
        "logo_url": "https://logo.clearbit.com/hul.co.in",
        "website": "https://www.hul.co.in",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "BAJFINANCE.NS",
        "company_name": "Bajaj Finance Limited",
        "sector": "Financial Services",
        "industry": "Credit Services",
        "exchange": "NSE",
        "current_price": 6850.00,
        "market_cap": 4200000000000.0,
        "description": "Bajaj Finance Limited operates as a non-banking financial company in India.",
        "logo_url": "https://logo.clearbit.com/bajajfinserv.in",
        "website": "https://www.bajajfinserv.in/finance",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "MARUTI.NS",
        "company_name": "Maruti Suzuki India Limited",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "exchange": "NSE",
        "current_price": 12200.00,
        "market_cap": 3800000000000.0,
        "description": "Maruti Suzuki India Limited manufactures, purchases, and sells motor vehicles, components, and spare parts in India and internationally.",
        "logo_url": "https://logo.clearbit.com/marutisuzuki.com",
        "website": "https://www.marutisuzuki.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "ASIANPAINT.NS",
        "company_name": "Asian Paints Limited",
        "sector": "Consumer Cyclical",
        "industry": "Specialty Retail",
        "exchange": "NSE",
        "current_price": 2850.40,
        "market_cap": 2700000000000.0,
        "description": "Asian Paints Limited manufactures, sells, and distributes paints, coatings, home decor products, and related services.",
        "logo_url": "https://logo.clearbit.com/asianpaints.com",
        "website": "https://www.asianpaints.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "HCLTECH.NS",
        "company_name": "HCL Technologies Limited",
        "sector": "Technology",
        "industry": "Information Technology Services",
        "exchange": "NSE",
        "current_price": 1620.10,
        "market_cap": 4400000000000.0,
        "description": "HCL Technologies Limited provides software development, business process outsourcing, and infrastructure management services.",
        "logo_url": "https://logo.clearbit.com/hcltech.com",
        "website": "https://www.hcltech.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "TATASTEEL.NS",
        "company_name": "Tata Steel Limited",
        "sector": "Basic Materials",
        "industry": "Steel",
        "exchange": "NSE",
        "current_price": 155.40,
        "market_cap": 1900000000000.0,
        "description": "Tata Steel Limited manufactures and distributes steel products in India and internationally.",
        "logo_url": "https://logo.clearbit.com/tatasteel.com",
        "website": "https://www.tatasteel.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "NTPC.NS",
        "company_name": "NTPC Limited",
        "sector": "Utilities",
        "industry": "Utilities - Regulated Electric",
        "exchange": "NSE",
        "current_price": 350.20,
        "market_cap": 3400000000000.0,
        "description": "NTPC Limited generates and sells bulk power to state power utilities in India.",
        "logo_url": "https://logo.clearbit.com/ntpc.co.in",
        "website": "https://www.ntpc.co.in",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "POWERGRID.NS",
        "company_name": "Power Grid Corporation of India Limited",
        "sector": "Utilities",
        "industry": "Utilities - Regulated Electric",
        "exchange": "NSE",
        "current_price": 280.40,
        "market_cap": 2600000000000.0,
        "description": "Power Grid Corporation of India Limited transmits bulk power across different states in India.",
        "logo_url": "https://logo.clearbit.com/powergrid.in",
        "website": "https://www.powergrid.in",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "ADANIENT.NS",
        "company_name": "Adani Enterprises Limited",
        "sector": "Industrials",
        "industry": "Conglomerates",
        "exchange": "NSE",
        "current_price": 3150.00,
        "market_cap": 3600000000000.0,
        "description": "Adani Enterprises Limited operates as a diversified conglomerate in India and internationally.",
        "logo_url": "https://logo.clearbit.com/adani.com",
        "website": "https://www.adanienterprises.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    },
    {
        "symbol": "M&M.NS",
        "company_name": "Mahindra & Mahindra Limited",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "exchange": "NSE",
        "current_price": 2050.80,
        "market_cap": 2550000000000.0,
        "description": "Mahindra & Mahindra Limited manufactures and sells passenger cars, commercial vehicles, and tractors in India.",
        "logo_url": "https://logo.clearbit.com/mahindra.com",
        "website": "https://www.mahindra.com",
        "country": "India",
        "currency": "INR",
        "is_active": True
    }
]

async def seed_stocks(db: AsyncIOMotorDatabase):
    """Seed the popular stocks database if it is empty."""
    stocks_collection = db["stocks"]
    count = await stocks_collection.count_documents({})
    if count == 0:
        logger.info("Stocks collection is empty. Seeding %d initial popular stocks...", len(POPULAR_STOCKS))
        now = datetime.now(timezone.utc)
        documents = []
        for stock_data in POPULAR_STOCKS:
            doc = {
                "symbol": stock_data["symbol"].upper(),
                "company_name": stock_data["company_name"],
                "sector": stock_data["sector"],
                "industry": stock_data["industry"],
                "exchange": stock_data["exchange"],
                "current_price": stock_data["current_price"],
                "market_cap": stock_data["market_cap"],
                "description": stock_data["description"],
                "logo_url": stock_data["logo_url"],
                "website": stock_data["website"],
                "country": stock_data["country"],
                "currency": stock_data["currency"],
                "is_active": stock_data["is_active"],
                "created_at": now,
                "updated_at": now
            }
            documents.append(doc)
        await stocks_collection.insert_many(documents)
        logger.info("Successfully seeded %d stocks.", len(documents))
    else:
        logger.info("Stocks database already has %d stocks. Skipping seed.", count)
